// <auto-generated />
using ChroniclesOfDarknessDiceRoller.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChroniclesOfDarknessDiceRoller.Server.Migrations
{
    [DbContext(typeof(DiceRollerContext))]
    [Migration("20220103002408_AddedDiceRoll")]
    partial class AddedDiceRoll
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("ChroniclesOfDarknessDiceRoller.Server.Model.DiceRoll", b =>
                {
                    b.Property<string>("GameName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GameName");

                    b.ToTable("DiceRolls");
                });
#pragma warning restore 612, 618
        }
    }
}
